### ISSUE TITLE
this is so bad

### ISSUE THREAD

**Issue by xxxOMA** [quickdaffy/Feather#2]
why bother even uploading this LOL

**Comment by quickdaffy** [comment]
why bother looking at it? still fanboying me
also you don’t get to talk when you paste rats lmao
you don’t make code even remotely as good as this, and it’s not even good

**Comment by xxxOMA** [comment]
Damn a whole 0 stars, so proud of you.... paste rats lol? The only thing pasted in omaBackdoor v0.2 is a method to get headers, I already rewrote the entire discord payload system in v0.3 LOL

And if you call this code good you're mentally ill...  you're depressed, that explains it

**Comment by quickdaffy** [comment]
never called it good code
you fully pasted the yoink rat and travis backdoor
you wont stop looking at my projects, stop fanboying me lmao
how many stars does omaBackdoor have? one? from you? yes?
fuck off?

**Comment by quickdaffy** [comment]
nobody likes you, just leave

**Comment by quickdaffy** [comment]
fold
