### ISSUE TITLE
fold

### ISSUE THREAD

**Issue by xxxOMA** [quickdaffy/Feather#3]
deleting the issue. cry harder, this code is ass and you know it Lmfao

Nice "Java Protection" services retard, legit pasting my wireshark detector LOL, you can't even make a AntiVM

**Comment by quickdaffy** [comment]
show me where I pasted your shit wireshark detector? the one where you can just rename the exe file to bypass it?
you're the one pasting rats over and over again
once again, literally nobody likes you
you can't make better code
cry harder

**Comment by quickdaffy** [comment]
going to just block you from posting issues on my repos at this point, your fanboying is starting to get on my nerves
